// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4941NS96jaix4-Asnm0uPzi24oiDmTc',
    appId: '1:623176519669:web:7d127b686745d1f2e6dabc',
    messagingSenderId: '623176519669',
    projectId: 'realtime-notification-app',
    authDomain: 'realtime-notification-app.firebaseapp.com',
    storageBucket: 'realtime-notification-app.firebasestorage.app',
    measurementId: 'G-MXT3KMY2VX',
    databaseURL: 'https://realtime-notification-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNixg9QozQefuRoQ0CISydWisY41fUEM',
    appId: '1:623176519669:android:a1b0f3ffc98036e1e6dabc',
    messagingSenderId: '623176519669',
    projectId: 'realtime-notification-app',
    storageBucket: 'realtime-notification-app.firebasestorage.app',
    databaseURL: 'https://realtime-notification-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi91hJQC8RsNN1Yncrs2i8Hve6a38G1o8',
    appId: '1:623176519669:ios:c96d9db893a6e0e3e6dabc',
    messagingSenderId: '623176519669',
    projectId: 'realtime-notification-app',
    storageBucket: 'realtime-notification-app.firebasestorage.app',
    iosBundleId: 'com.example.realtimeNotificationApp',
    databaseURL: 'https://realtime-notification-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi91hJQC8RsNN1Yncrs2i8Hve6a38G1o8',
    appId: '1:623176519669:ios:c96d9db893a6e0e3e6dabc',
    messagingSenderId: '623176519669',
    projectId: 'realtime-notification-app',
    storageBucket: 'realtime-notification-app.firebasestorage.app',
    iosBundleId: 'com.example.realtimeNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn4941NS96jaix4-Asnm0uPzi24oiDmTc',
    appId: '1:623176519669:web:14015f65334ba3fbe6dabc',
    messagingSenderId: '623176519669',
    projectId: 'realtime-notification-app',
    authDomain: 'realtime-notification-app.firebaseapp.com',
    storageBucket: 'realtime-notification-app.firebasestorage.app',
    measurementId: 'G-P20J8KMBCM',
  );
}
